### ISSUE TITLE
Error when trying to connect broker without any authentification

### ISSUE THREAD

**Issue by ptaillard** [disaster37/activemq#15]
Hi,
I  use the last image release 5.13.1 and using default settings.
When my app try to connect to this container, i have the following error message:
**_Cause: User name [null] or password is invalid_**
I want to connect to my broker without any authentification.
How can i do this with the latest release?

Thanks,

**Comment by DingGuodong** [comment]
Hi,
I use this latest images too, and I also meet this error:
**"Caught: javax.jms.JMSSecurityException: User name [xxx] or password is invalid.
javax.jms.JMSSecurityException: User name [xxx] or password is invalid."**
My boot option is:

```
docker run --restart="always" --name='server1-activemq-01-master' --net interconnection -d --hostname=server1-activemq-01-master \
-e 'ACTIVEMQ_NAME=amqp-srv1-master' \
-e 'ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true' \
-e 'ACTIVEMQ_ADMIN_LOGIN=admin' -e 'ACTIVEMQ_ADMIN_PASSWORD=your_password' \
-e 'ACTIVEMQ_WRITE_LOGIN=producer_login' -e 'ACTIVEMQ_WRITE_PASSWORD=producer_password' \
-e 'ACTIVEMQ_READ_LOGIN=consumer_login' -e 'ACTIVEMQ_READ_PASSWORD=consumer_password' \
-e 'ACTIVEMQ_JMX_LOGIN=jmx_login' -e 'ACTIVEMQ_JMX_PASSWORD=jmx_password' \
-e 'ACTIVEMQ_STATIC_TOPICS=topic1;topic2;topic3' \
-e 'ACTIVEMQ_STATIC_QUEUES=queue1;queue2;queue3' \
-e 'ACTIVEMQ_MIN_MEMORY=1024' -e  'ACTIVEMQ_MAX_MEMORY=4096' \
-e 'ACTIVEMQ_ENABLED_SCHEDULER=true' \
-v /data/docker/activemq/data:/data/activemq \
-v /data/docker/activemq/data/kahadb:/data/activemq/kahadb \
-v /data/docker/activemq/log-master:/var/log/activemq \
-v /data/docker/activemq/conf/activemq.xml:/opt/activemq/conf/activemq.xml \
-p 8161:8161 \
-p 61616:61616 \
-p 61613:61613 \
webcenter/activemq
```

I think there must be a mistake in this version of this docker image. 
================This is segment line ================
so I retry with this:
`
docker run --restart="always" --name='activemq-03' -d --hostname=activemq-03 \
-e 'ACTIVEMQ_NAME=amqp-srv3' \
-e 'ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true' \
-e 'ACTIVEMQ_ADMIN_LOGIN=test' -e 'ACTIVEMQ_ADMIN_PASSWORD=test' \
-e 'ACTIVEMQ_WRITE_LOGIN=test' -e 'ACTIVEMQ_WRITE_PASSWORD=test' \
-e 'ACTIVEMQ_READ_LOGIN=test' -e 'ACTIVEMQ_READ_PASSWORD=test' \
-e 'ACTIVEMQ_JMX_LOGIN=test' -e 'ACTIVEMQ_JMX_PASSWORD=test' \
-e 'ACTIVEMQ_STATIC_TOPICS=topic1;topic2;topic3' \
-e 'ACTIVEMQ_STATIC_QUEUES=queue1;queue2;queue3' \
-e 'ACTIVEMQ_MIN_MEMORY=1024' -e  'ACTIVEMQ_MAX_MEMORY=4096' \
-e 'ACTIVEMQ_ENABLED_SCHEDULER=true' \
-p 8161:8161 \
-p 61616:61616 \
-p 61613:61613 \
webcenter/activemq
`
**At last, I find that only set "-e 'ACTIVEMQ_ADMIN_LOGIN=yourName' -e 'ACTIVEMQ_ADMIN_PASSWORD=yourPassword' \" like this self can login success, then I got a success!**
:100: 
Good luck and best regards.

**Comment by disaster37** [comment]
Sorry for that. I will investigate about this

**Comment by disaster37** [comment]
@ptaillard 

Can you try with the new release on develop branch ? You can now add -e ACTIVEMQ_ENABLED_AUTH=false to allow anonymous access.

docker run -ti --rm  -e ACTIVEMQ_ENABLED_AUTH=false -p 8161:8161 -p 61616:61616 -p 61613:61613 webcenter/activemq:test

Can you say me if is ok for you before to cretae the next release

**Comment by disaster37** [comment]
@DingGuodong 

Can you test the next release to say me if is ok ?

I have try with the following and no problem gor me:

docker run -ti --rm --name='server1-activemq-01-master' --hostname=server1-activemq-01-master -e 'ACTIVEMQ_NAME=amqp-srv1-master' -e 'ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true' -e 'ACTIVEMQ_ADMIN_LOGIN=admin' -e 'ACTIVEMQ_ADMIN_PASSWORD=your_password' -e 'ACTIVEMQ_WRITE_LOGIN=producer_login' -e 'ACTIVEMQ_WRITE_PASSWORD=producer_password' -e 'ACTIVEMQ_READ_LOGIN=consumer_login' -e 'ACTIVEMQ_READ_PASSWORD=consumer_password' -e 'ACTIVEMQ_OWNER_LOGIN=owner_login' -e 'ACTIVEMQ_OWNER_PASSWORD=owner_password' -e 'ACTIVEMQ_JMX_LOGIN=jmx_login' -e 'ACTIVEMQ_JMX_PASSWORD=jmx_password' -e 'ACTIVEMQ_STATIC_TOPICS=topic1;topic2;topic3' -e 'ACTIVEMQ_STATIC_QUEUES=queue1;queue2;queue3' -e 'ACTIVEMQ_MIN_MEMORY=1024' -e  'ACTIVEMQ_MAX_MEMORY=4096' -e 'ACTIVEMQ_ENABLED_SCHEDULER=true' -v /data/docker/activemq/data:/data/activemq -p 8161:8161 -p 61616:61616 -p 61613:61613 webcenter/activemq:test

> To use Read account and Write account, you queue or topic must be already exist. Else, for dynamic que, you must use OWNER account.

Can you say me if is ok for you before to cretae the next release

**Comment by ptaillard** [comment]
Thanks for your answer @DingGuodong and @disaster37.
@disaster37 : I will check your fix this monday and send you the result!

**Comment by pmihalcin** [comment]
@disaster37 
Hi there,
I experience the same problem and I'd like to elaborate on that with more details to help you troubleshoot the problem:

I used the command above to prepare activemq docker container

When I use this tutorial https://spring.io/guides/gs/messaging-jms/ and add following properties
**spring.activemq.broker-url=tcp://${DOCKER_MACHINE_IP:61616
spring.activemq.user=admin
spring.activemq.password=your_password**
then everything works

When I use http://gatling.io/docs/2.1.1/jms.html
and define jms protocol as follows (similar to the one above):
**val jmsConfig = jms
    .connectionFactoryName("ConnectionFactory")
    .url("tcp://${DOCKER_MACHINE_IP}:61616")
    .credentials("admin", "your_password")
    .contextFactory("org.apache.activemq.jndi.ActiveMQInitialContextFactory")
    .listenerCount(1)**

I am getting the exception mentioned in this issue:
Caused by: javax.security.auth.login.FailedLoginException: user name is null
    at org.apache.activemq.jaas.PropertiesLoginModule.login(PropertiesLoginModule.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)

I assume the problem occurs in particular circumstances.
Hopefullly, this gives you enough details
Thanks

**Comment by disaster37** [comment]
Hum, I think is a problem with your code or your API. It's like it never send the credential, so ActiveMQ throw FailedLoginExecption.

Maybee you can try with alpha version and you disable auth (-e ACTIVEMQ_ENABLED_AUTH=false) and you not send credential ...

**Comment by pmihalcin** [comment]
Yes, you were right. I had to change URL from tcp to vm

**Comment by ptaillard** [comment]
@disaster37 sorry for my late response.... But everything is ok on the test branch for this feature.
Thanks a lot for your reactivity and your work!

**Comment by disaster37** [comment]
Thanks for your feedback. I publish new release ;)
