### ISSUE TITLE
How to pass ACTIVEMQ_OPTS

### ISSUE THREAD

**Issue by mping** [disaster37/activemq#16]
I'd like to supply a java agent to this activemq image, but simply setting the ACTIVEMQ_OPTS doesn't seem to work. I guess current env properties should be passed-through to activemq, or at least all properties that start with "ACTIVEMQ_"

**Comment by disaster37** [comment]
I never use it, but it must work.
When read the supervisor documentation, it say that all supervisor process inehrit of all environment variable linken to shell start it.

And the supervisor call the official start script "/opt/activemq/bin/linux-x86-64/activemq console"

**Comment by mping** [comment]
I tried it but it didn't work. Server should be suspended upon start (it works locally):

`docker run --rm -P --name amq -e ACTIVEMQ_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005" webcenter/activemq:5.13.2`

**Comment by mping** [comment]
@disaster37 please see PR #17
